### ISSUE TITLE
Missing file: dataloader.datasets

### ISSUE THREAD

**Issue by Pluima** [HaoWang420/Gradient-guided-Modality-Decoupling#2]
ModuleNotFoundError: No module named 'dataloaders.datasets'

**Comment by night-gale** [comment]
Hi,

Sorry for the inconvenience. The problem is probably because I add `datasets` in the `.gitignore`, which was originally intended to ignore the actual data folder. Anyways, I've added the datasets folder under dataloaders in the newest commit and fixed the `.gitignore`. Hope that addresses the problem.

Cheers

**Comment by Pluima** [comment]
Problem solved.
Thanks very much!
